name: test
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
      - run: cd projects/ngx-mugen-scroll && npm version prerelease && cd -
      - run: npm run build-dist && cd dist/ngx-mugen-scroll && npm publish --tag beta
