name: deploy-beta
on:
  push:
    tags:
      - qa
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
      - run: npm run build-dist && cd dist/ngx-mugen-scroll && npm publish --tag beta && cd -
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
